Ignore the value attribute of <input type="file">
Browsers do the same thing, see
http://stackoverflow.com/questions/20537696/remember-and-repopulate-file-input/20537822#20537822

Without this, submitting the form as is gives
ValueError: upload_files need to be a list of tuples of (fieldname, filename, filecontent, mimetype) or (fieldname, filename, filecontent) or (fieldname, filename); you gave: "['file-field', u's', u'o', u'm', u'e', u'/', u'p', u'a', u't', u'h', u'/', u'f', u'i', u'l', u'e', u"